package com.dhbw.tutorsystem.mails;

public enum MailType {
    REGISTRATION,
    RESET_PASSWORD,
    TUTORIAL_PARTICIPATION_STUDENT,
    TUTORIAL_PARTICIPATION_REMOVAL_STUDENT,
    UNREGISTERD_USER_ADDED_TO_TUTORIAL,
    TUTORIAL_DELETION,
    USER_ADDED_TO_TUTORIAL,
    TUTOR_ADDED_ANNOUNCEMENT_MAIL,
    TUTOR_ADDED_ANNOUNCEMENT_MAIL_TO_TUTOR,
    TUTORIAL_REMOVED_MAIL_TO_STUDENT,
}
