package com.dhbw.tutorsystem.mails;

public enum MailType {
    REGISTRATION,
    RESET_PASSWORD,
    TUTORIAL_DELETION_WITH_REASON,
    TUTORIAL_DELETION,
    TUTORIAL_PARTICIPATION,
    UNREGISTERD_USER_ADDED_TO_TUTORIAL,
    USER_ADDED_TO_TUTORIAL
}
