version: '3.7'

services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
          # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
          USER_UID: 1000
          USER_GID: 1000
    user: "1000:1000"
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/workspace
    ports:
      - 8080:8080
    command: sleep infinity

